version: '3.9'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
      - cache
      - recommender
      - web
    restart: always
    environment:
      - STATE=SUT
  db:
    container_name: db
    image: 'mysql:8.0.31-debian'
    platform: linux/x86_64
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: db_host
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "3333:80"

  cache:
    container_name: cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

  recommender:
    container_name: recommender
    image: teabreak/recommender_service:latest
    restart: always
    ports:
      - '9180:9180'
  web:
    container_name: web
    image: teabreak/thessis-web:latest
    restart: always
    ports:
      - '3000:3000'
    environment:
      STATE: SUT

volumes:
  dbdata:

networks:
  server:
    driver: bridge

