apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: thesis-ingress

spec:
  rules:
    - host: web.thesis.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 3000
    - host: db.thesis.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: db-host-service
                port:
                  number: 3333
    - host: be.thesis.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecommerce-service
                port:
                  number: 8082


