apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: thesis-ingress

spec:
  rules:
      - http:
          paths:
            - path: /web
              pathType: Prefix
              backend:
                service:
                  name: web-service
                  port:
                    number: 3000
            - path: /db
              pathType: Prefix
              backend:
                service:
                  name: db-host-service
                  port:
                    number: 3333
            - path: /server
              pathType: Prefix
              backend:
                service:
                  name: ecommerce-service
                  port:
                    number: 8082



