// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package grpc_base

import (
	"github.com/eNViDAT0001/Thesis/Backend/delivery/grpc/services/recommender"
)

// Injectors from grpc_wire.go:

func initGRPCCollection() *GRPCCollection {
	grpcService := recommender.NewRecommenderService()
	grpcCollection := NewGRPCCollection(grpcService)
	return grpcCollection
}
