PORT: 8082

VERSION: v0.5.0 # must follow pattern vXX.XX.XX for auto tag in CI

DB_HOST: localhost
DB_PORT: 3306
DB_NAME: ecommerce_db
DB_USER: admin
DB_PASSWORD: admin

RECOMMENDER:
  HOST: 127.0.0.1
  PORT: 9180

REDIS:
  HOST: localhost
  PORT: 6379
  PASSWORD: ""
  DB: 0

FE:
  HOST: localhost
  PORT: 3000

CLOUDINARY:
  NAME: damzcas3k
  API_KEY: 332611833886276
  API_SECRET: CApeUOYt-JIgUSj9LvSAs6rO610
  SECURE: true

PAYPAL:
  CLIENT_KEY: AX9WdkaCNJGWFk3YQBUoa1YOrDw_fdZqBG9AZ61fwJRMhgMIWTl-6vmTCWjSRDianCA9vMEeSBLBqvs5
  SECRET_KEY: EDuzsUItn347wt6uhkRq3zPXtdAJkMR1pAZLwfU7SrwVVfsBll4OVmTjzNYxZvpkJA42zUW04fM01-Wm

GOOGLE_OAUTH2:
  CLIENT_ID: 549552897559-8tjjltibp1193mkk4vj8cnh3f8ool0lb.apps.googleusercontent.com
  PROJECT_ID: ecommerce-quest
  AUTH_URI: https://accounts.google.com/o/oauth2/auth
  TOKEN_URI: https://oauth2.googleapis.com/token
  AUTH_PROVIDER_X509_CERT_URL: https://www.googleapis.com/oauth2/v1/certs
  CLIENT_SECRET: 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
  REDIRECT_URL: http://localhost:8082/api/v1/app/login/google/callback

MAIL_SHOP: dummyshophaha@gmail.com
# 24h
ACCESS_TOKEN_EXPIRE_IN_MINUTE: 1000
# 7 days
REFRESH_TOKEN_EXPIRE_IN_DAYS: 7
TOKEN_SECRET: "SuPerSecreTBeliEvEmE"

